import React, { useState, useEffect } from 'react';
import useStore from '../store';
import AboutUs from './AboutUs';
import HoverText from './HoverText';

export default function Overlay() {
  const stage = useStore((s) => s.stage);
  const activePortal = useStore((s) => s.activePortal);
  const portalScreenPos = useStore((s) => s.portalScreenPos);
  const expandedPortal = useStore((s) => s.expandedPortal);
  const aboutUsVisible = useStore((s) => s.aboutUsVisible);
  const teamVisible = useStore((s) => s.teamVisible);
  const setAboutUsVisible = useStore((s) => s.setAboutUsVisible);
  const setTeamVisible = useStore((s) => s.setTeamVisible);
  const setExpandedPortal = useStore((s) => s.setExpandedPortal);
  const setActivePortal = useStore((s) => s.setActivePortal);
  const reset = () => { useStore.getState().setStage(3); useStore.getState().setActivePortal(null); };
  const [menuOpen, setMenuOpen] = useState(false);
  const [isWide, setIsWide] = useState(typeof window !== 'undefined' && window.innerWidth / window.innerHeight >= 1.2);
  useEffect(() => { setMenuOpen(false); }, [stage]);
  useEffect(() => { const h = () => setIsWide(window.innerWidth / window.innerHeight >= 1.2); window.addEventListener('resize', h); return () => window.removeEventListener('resize', h); }, []);
  const pageOpen = aboutUsVisible || teamVisible;
  const textOffset = expandedPortal === 'portalA' ? (isWide ? { paddingLeft: '30vw' } : { paddingLeft: 0, paddingRight: 0 }) : (isWide ? { paddingRight: '30vw' } : { paddingLeft: 0, paddingRight: 0 });
  const detailCn = activePortal === 'portalA' ? '定制化IP开发' : '消失的文明系列';
  const detailEn = activePortal === 'portalA' ? 'Custom IP Development' : 'Lost Civilizations Series';
  const expandedText = expandedPortal === 'portalA' ? { title: '定制化IP开发', subtitle: '数字化文旅实践案例', body: '零想联合德清文旅打造的全国首个古镇神话主题IP《寻剑》，串联德清莫干山、下渚湖、新市古镇三大名片，展现干将莫邪神话传说场景，让游客戴上眼镜即可穿越千年。' } : { title: '聚焦消失的文明系列开发', subtitle: '探索人类的文明史，IP受众广、生命周期长', body: '零想自研《奇幻巴比伦》是全球首个巴比伦文明XR沉浸式探索体验，在虚拟世界中重现了空中花园、伊什塔尔门与巴别塔的奇观，这不仅是技术的展示，更是一次跨越两千多年的文明对话。' };
  return (<>
    {((stage === 0) || aboutUsVisible || teamVisible) && (<div style={{ position: 'fixed', bottom: 0, left: 0, right: 0, height: '40vh', zIndex: 5, pointerEvents: 'none', background: 'radial-gradient(ellipse 80% 100% at 50% 100%, rgba(30, 50, 120, 0.9) 0%, rgba(15, 25, 80, 0.5) 40%, transparent 70%)' }} />)}
    {!pageOpen && (<div style={{ position: 'fixed', top: 'clamp(1rem, 4vw, 2rem)', left: 'clamp(1rem, 4vw, 2rem)', zIndex: 20, display: 'flex', flexDirection: 'row', alignItems: 'flex-end' }}><img src='/assets/logo-text.svg' alt='LINGX' onClick={(e) => { e.stopPropagation(); setMenuOpen(!menuOpen); }} style={{ width: 'clamp(60px, 8vw, 100px)', opacity: stage === 0 ? 0.55 : 0, filter: 'brightness(2.5)', userSelect: 'none', pointerEvents: stage === 0 ? 'auto' : 'none', cursor: 'pointer', transition: 'opacity 1s ease', flexShrink: 0 }} /><div style={{ maxWidth: menuOpen ? '200px' : '0', opacity: menuOpen ? 1 : 0, overflow: 'hidden', marginLeft: '0.8rem', transform: menuOpen ? 'translateX(0)' : 'translateX(-10px)', transition: 'max-width 0.5s ease, opacity 0.4s ease, transform 0.4s ease', display: 'flex', flexDirection: 'row', gap: '1.2rem', whiteSpace: 'nowrap' }}><p onClick={(e) => { e.stopPropagation(); setActivePortal(null); setExpandedPortal(null); setAboutUsVisible(true); setMenuOpen(false); }} style={{ color: 'rgba(255,252,248,0.55)', fontWeight: 300, fontSize: '0.75rem', letterSpacing: '0.12em', margin: 0, userSelect: 'none', cursor: 'pointer', pointerEvents: 'auto' }}>About Us</p><p onClick={(e) => { e.stopPropagation(); setActivePortal(null); setExpandedPortal(null); setTeamVisible(true); setMenuOpen(false); }} style={{ color: 'rgba(255,252,248,0.55)', fontWeight: 300, fontSize: '0.75rem', letterSpacing: '0.12em', margin: 0, userSelect: 'none', cursor: 'pointer', pointerEvents: 'auto' }}>Team</p></div></div>)}
    <div style={{ position: 'fixed', inset: 0, zIndex: 10, pointerEvents: 'none', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'flex-end', paddingBottom: '18vh', opacity: (stage < 2 && !pageOpen) ? 1 : 0, transition: 'opacity 1.5s ease' }}><h1 style={{ color: 'rgba(245, 240, 232, 0.4)', fontWeight: 300, fontSize: 'clamp(1rem, 2.5vw, 2rem)', letterSpacing: '0.25em', textAlign: 'center', lineHeight: 1.6, margin: 0, userSelect: 'none' }}><HoverText text="点亮每个人心中的梦境" as="h1" style={{ display:'inline', color: 'rgba(245, 240, 232, 0.4)', fontWeight:300, fontSize: 'clamp(1rem, 2.5vw, 2rem)', letterSpacing: '0.25em', textAlign: 'center', lineHeight: 1.6, margin: 0, userSelect: 'none' }} /></h1><p style={{ color: 'rgba(245, 240, 232, 0.3)', fontWeight: 200, fontSize: 'clamp(0.6rem, 1.2vw, 0.85rem)', letterSpacing: '0.25em', margin: '0.6rem 0 0 0', userSelect: 'none' }}><HoverText text="LIGHT UP YOUR DREAMWORLD" as="p" style={{ display:'inline', color: 'rgba(245, 240, 232, 0.3)', fontWeight:200, fontSize: 'clamp(0.6rem, 1.2vw, 0.85rem)', letterSpacing: '0.25em', margin: '0.6rem 0 0 0', userSelect: 'none' }} /></p></div>
    {activePortal && stage >= 2 && !expandedPortal && (<div style={{ position: 'fixed', left: portalScreenPos.x, top: portalScreenPos.y, transform: 'translate(-50%, -50%)', zIndex: 25, pointerEvents: 'none', textAlign: 'center' }}><h2 style={{ color: 'rgba(255, 252, 248, 0.85)', fontWeight: 300, fontSize: 'clamp(0.8rem, 1.6vw, 1.3rem)', letterSpacing: '0.2em', margin: 0, userSelect: 'none', whiteSpace: 'nowrap' }}>{detailCn}</h2><p style={{ color: 'rgba(255, 252, 248, 0.55)', fontWeight: 300, fontSize: 'clamp(0.55rem, 0.9vw, 0.75rem)', letterSpacing: '0.15em', margin: '0.3rem 0 0 0', userSelect: 'none', whiteSpace: 'nowrap' }}>{detailEn}</p></div>)}
    {expandedPortal && stage >= 2 && (<div onClick={() => { setExpandedPortal(null); setActivePortal(expandedPortal); }} style={{ position: 'fixed', inset: 0, zIndex: 35, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', animation: 'fadeIn 1s ease', ...textOffset }}><div style={{ maxWidth: isWide ? '500px' : '350px', width: isWide ? '90%' : '70%', textAlign: isWide ? 'left' : 'center', margin: isWide ? '0' : (expandedPortal === 'portalA' ? '35vh 0 0 0' : '-30vh 0 0 0'), animation: 'slideUp 1s ease' }}><p style={{ color: 'rgba(255,252,248,0.7)', fontSize: 'clamp(1rem, 1.5vw, 1.3rem)', letterSpacing: '0.1em', margin: '0 0 0.5rem 0', fontWeight: 400, userSelect: 'none' }}>{expandedText.title}</p><p style={{ color: 'rgba(255,252,248,0.45)', fontWeight: 300, fontSize: 'clamp(0.7rem, 1vw, 0.85rem)', letterSpacing: '0.08em', margin: '0 0 1.5rem 0', userSelect: 'none' }}>{expandedText.subtitle}</p><p style={{ color: 'rgba(255,252,248,0.5)', fontWeight: 300, fontSize: 'clamp(0.75rem, 1.1vw, 0.9rem)', lineHeight: 2, letterSpacing: '0.06em', margin: 0, userSelect: 'none' }}>{expandedText.body}</p></div></div>)}
    {stage === 2 && !pageOpen && (<div onClick={(e) => { e.stopPropagation(); reset(); useStore.getState().setActivePortal(null); useStore.getState().setExpandedPortal(null); }} style={{ position: 'fixed', bottom: '2.5rem', left: '50%', transform: 'translateX(-50%)', zIndex: 30, pointerEvents: 'auto', cursor: 'pointer', textAlign: 'center', animation: 'breathe 3s ease-in-out infinite', userSelect: 'none' }}><p style={{ color: 'rgba(245, 240, 232, 0.4)', fontWeight: 300, fontSize: '0.85rem', letterSpacing: '0.2em', margin: 0 }}><HoverText text="返回源点" as="span" style={{ display:'inline', color: 'inherit', fontWeight:300, fontSize: 'inherit', letterSpacing: 'inherit' }} /></p><p style={{ color: 'rgba(245, 240, 232, 0.2)', fontWeight: 300, fontSize: '0.65rem', letterSpacing: '0.15em', margin: '0.3rem 0 0 0' }}><HoverText text="RETURN TO SOURCE" as="span" style={{ display:'inline', color: 'inherit', fontWeight:300, fontSize: 'inherit', letterSpacing: 'inherit' }} /></p></div>)}
    <AboutUs />
    {teamVisible && (<div style={{ position: 'fixed', inset: 0, zIndex: 25, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', pointerEvents: 'none', animation: 'fadeIn 1.5s ease, teamBreathe 6s ease-in-out infinite' }}><h2 style={{ color: 'rgba(255,252,248,0.7)', fontWeight: 300, fontSize: 'clamp(0.9rem, 1.8vw, 1.5rem)', letterSpacing: '0.15em', textAlign: 'center', userSelect: 'none', margin: 0, maxWidth: '90vw', padding: '0 1rem', lineHeight: 1.8 }}><HoverText text="我们是零想 XR 梦工厂，为点亮每个人心中的梦境。" as="h2" style={{ display:'inline', color: 'rgba(255,252,248,0.7)', fontWeight:300, fontSize: 'clamp(0.9rem, 1.8vw, 1.5rem)', letterSpacing: '0.15em', textAlign: 'center', userSelect: 'none', margin: 0, maxWidth: '90vw', padding: '0 1rem', lineHeight: 1.8 }} /></h2><p style={{ color: 'rgba(255,252,248,0.35)', fontWeight: 200, fontSize: 'clamp(0.6rem, 0.9vw, 0.8rem)', letterSpacing: '0.1em', textAlign: 'center', userSelect: 'none', margin: '0.6rem 0 0 0', maxWidth: '85vw', padding: '0 1rem', lineHeight: 1.8 }}><HoverText text="WE ARE LINGX DreamWorks. LIGHT UP YOUR DREAMWORLD" as="p" style={{ display:'inline', color: 'rgba(255,252,248,0.35)', fontWeight:200, fontSize: 'clamp(0.6rem, 0.9vw, 0.8rem)', letterSpacing: '0.1em', textAlign: 'center', userSelect: 'none', margin: '0.6rem 0 0 0', maxWidth: '85vw', padding: '0 1rem', lineHeight: 1.8 }} /></p></div>)}
    {teamVisible && (<div onClick={() => setTeamVisible(false)} style={{ position: 'fixed', bottom: '2.5rem', left: '50%', transform: 'translateX(-50%)', zIndex: 45, pointerEvents: 'auto', cursor: 'pointer', textAlign: 'center', animation: 'breathe 3s ease-in-out infinite', userSelect: 'none' }}><p style={{ color: 'rgba(245, 240, 232, 0.4)', fontWeight: 300, fontSize: '0.85rem', letterSpacing: '0.2em', margin: 0 }}><HoverText text="返回源点" as="span" style={{ display:'inline', color: 'inherit', fontWeight:300, fontSize: 'inherit', letterSpacing: 'inherit' }} /></p><p style={{ color: 'rgba(245, 240, 232, 0.2)', fontWeight: 300, fontSize: '0.65rem', letterSpacing: '0.15em', margin: '0.3rem 0 0 0' }}><HoverText text="RETURN TO SOURCE" as="span" style={{ display:'inline', color: 'inherit', fontWeight:300, fontSize: 'inherit', letterSpacing: 'inherit' }} /></p></div>)}
    <style>{'@keyframes breathe{0%,100%{opacity:0.5}50%{opacity:1}}@keyframes fadeIn{from{opacity:0}to{opacity:1}}@keyframes teamBreathe{0%,100%{opacity:0.7}50%{opacity:0.85}}@keyframes slideUp{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}'}</style>
  </>);
}




